%% pairs are disregarded

hardAction(hit, 2,  4).
hardAction(hit, 2,  5).
hardAction(hit, 2,  6).
hardAction(hit, 2,  7).
hardAction(hit, 2,  8).
hardAction(hit, 2,  9).
hardAction(hit, 2, 10).
hardAction(hit, 2, 11).
hardAction(hit, 2, 12).
hardAction(stand, 2, 13).
hardAction(stand, 2, 14).
hardAction(stand, 2, 15).
hardAction(stand, 2, 16).
hardAction(stand, 2, 17).
hardAction(stand, 2, 18).
hardAction(stand, 2, 19).
hardAction(stand, 2, 20).

hardAction(hit, 3,  4).
hardAction(hit, 3,  5).
hardAction(hit, 3,  6).
hardAction(hit, 3,  7).
hardAction(hit, 3,  8).
hardAction(hit, 3,  9).
hardAction(hit, 3, 10).
hardAction(hit, 3, 11).
hardAction(hit, 3, 12).
hardAction(stand, 3, 13).
hardAction(stand, 3, 14).
hardAction(stand, 3, 15).
hardAction(stand, 3, 16).
hardAction(stand, 3, 17).
hardAction(stand, 3, 18).
hardAction(stand, 3, 19).
hardAction(stand, 3, 20).

hardAction(hit, 4,  4).
hardAction(hit, 4,  5).
hardAction(hit, 4,  6).
hardAction(hit, 4,  7).
hardAction(hit, 4,  8).
hardAction(hit, 4,  9).
hardAction(hit, 4, 10).
hardAction(hit, 4, 11).
hardAction(stand, 4, 12).
hardAction(stand, 4, 13).
hardAction(stand, 4, 14).
hardAction(stand, 4, 15).
hardAction(stand, 4, 16).
hardAction(stand, 4, 17).
hardAction(stand, 4, 18).
hardAction(stand, 4, 19).
hardAction(stand, 4, 20).

hardAction(hit, 5,  4).
hardAction(hit, 5,  5).
hardAction(hit, 5,  6).
hardAction(hit, 5,  7).
hardAction(hit, 5,  8).
hardAction(hit, 5,  9).
hardAction(hit, 5, 10).
hardAction(hit, 5, 11).
hardAction(stand, 5, 12).
hardAction(stand, 5, 13).
hardAction(stand, 5, 14).
hardAction(stand, 5, 15).
hardAction(stand, 5, 16).
hardAction(stand, 5, 17).
hardAction(stand, 5, 18).
hardAction(stand, 5, 19).
hardAction(stand, 5, 20).

hardAction(hit, 6,  4).
hardAction(hit, 6,  5).
hardAction(hit, 6,  6).
hardAction(hit, 6,  7).
hardAction(hit, 6,  8).
hardAction(hit, 6,  9).
hardAction(hit, 6, 10).
hardAction(hit, 6, 11).
hardAction(stand, 6, 12).
hardAction(stand, 6, 13).
hardAction(stand, 6, 14).
hardAction(stand, 6, 15).
hardAction(stand, 6, 16).
hardAction(stand, 6, 17).
hardAction(stand, 6, 18).
hardAction(stand, 6, 19).
hardAction(stand, 6, 20).

hardAction(hit, 7,  4).
hardAction(hit, 7,  5).
hardAction(hit, 7,  6).
hardAction(hit, 7,  7).
hardAction(hit, 7,  8).
hardAction(hit, 7,  9).
hardAction(hit, 7, 10).
hardAction(hit, 7, 11).
hardAction(hit, 7, 12).
hardAction(hit, 7, 13).
hardAction(hit, 7, 14).
hardAction(hit, 7, 15).
hardAction(hit, 7, 16).
hardAction(stand, 7, 17).
hardAction(stand, 7, 18).
hardAction(stand, 7, 19).
hardAction(stand, 7, 20).

hardAction(hit, 8,  4).
hardAction(hit, 8,  5).
hardAction(hit, 8,  6).
hardAction(hit, 8,  7).
hardAction(hit, 8,  8).
hardAction(hit, 8,  9).
hardAction(hit, 8, 10).
hardAction(hit, 8, 11).
hardAction(hit, 8, 12).
hardAction(hit, 8, 13).
hardAction(hit, 8, 14).
hardAction(hit, 8, 15).
hardAction(hit, 8, 16).
hardAction(stand, 8, 17).
hardAction(stand, 8, 18).
hardAction(stand, 8, 19).
hardAction(stand, 8, 20).

hardAction(hit, 9,  4).
hardAction(hit, 9,  5).
hardAction(hit, 9,  6).
hardAction(hit, 9,  7).
hardAction(hit, 9,  8).
hardAction(hit, 9,  9).
hardAction(hit, 9, 10).
hardAction(hit, 9, 11).
hardAction(hit, 9, 12).
hardAction(hit, 9, 13).
hardAction(hit, 9, 14).
hardAction(hit, 9, 15).
hardAction(hit, 9, 16).
hardAction(stand, 9, 17).
hardAction(stand, 9, 18).
hardAction(stand, 9, 19).
hardAction(stand, 9, 20).

hardAction(hit, 10,  4).
hardAction(hit, 10,  5).
hardAction(hit, 10,  6).
hardAction(hit, 10,  7).
hardAction(hit, 10,  8).
hardAction(hit, 10,  9).
hardAction(hit, 10, 10).
hardAction(hit, 10, 11).
hardAction(hit, 10, 12).
hardAction(hit, 10, 13).
hardAction(hit, 10, 14).
hardAction(hit, 10, 15).
hardAction(hit, 10, 16).
hardAction(stand, 10, 17).
hardAction(stand, 10, 18).
hardAction(stand, 10, 19).
hardAction(stand, 10, 20).

hardAction(hit, ace,  4).
hardAction(hit, ace,  5).
hardAction(hit, ace,  6).
hardAction(hit, ace,  7).
hardAction(hit, ace,  8).
hardAction(hit, ace,  9).
hardAction(hit, ace, 10).
hardAction(hit, ace, 11).
hardAction(hit, ace, 12).
hardAction(hit, ace, 13).
hardAction(hit, ace, 14).
hardAction(hit, ace, 15).
hardAction(hit, ace, 16).
hardAction(stand, ace, 17).
hardAction(stand, ace, 18).
hardAction(stand, ace, 19).
hardAction(stand, ace, 20).



%% softAction(Action, Face up dealer, Player's Total).
softAction(hit,   2, 2).
softAction(hit,   2, 3).
softAction(hit,   2, 4).
softAction(hit,   2, 5).
softAction(hit,   2, 6).
softAction(stand, 2, 7).
softAction(stand, 2, 8).
softAction(stand, 2, 9).
softAction(hit, 2, 11).%ace

softAction(hit,   3, 2).
softAction(hit,   3, 3).
softAction(hit,   3, 4).
softAction(hit,   3, 5).
softAction(hit,   3, 6).
softAction(stand, 3, 7).
softAction(stand, 3, 8).
softAction(stand, 3, 9).
softAction(hit, 3, 11).%ace

softAction(hit,   4, 2).
softAction(hit,   4, 3).
softAction(hit,   4, 4).
softAction(hit,   4, 5).
softAction(hit,   4, 6).
softAction(stand, 4, 7).
softAction(stand, 4, 8).
softAction(stand, 4, 9).
softAction(hit, 4, 11).%ace

softAction(hit,   5, 2).
softAction(hit,   5, 3).
softAction(hit,   5, 4).
softAction(hit,   5, 5).
softAction(hit,   5, 6).
softAction(stand, 5, 7).
softAction(stand, 5, 8).
softAction(stand, 5, 9).
softAction(hit, 5, 11).%ace

softAction(hit,   6, 2).
softAction(hit,   6, 3).
softAction(hit,   6, 4).
softAction(hit,   6, 5).
softAction(hit,   6, 6).
softAction(stand, 6, 7).
softAction(stand, 6, 8).
softAction(stand, 6, 9).
softAction(hit, 6, 11).%ace

softAction(hit,   7, 2).
softAction(hit,   7, 3).
softAction(hit,   7, 4).
softAction(hit,   7, 5).
softAction(hit,   7, 6).
softAction(stand, 7, 7).
softAction(stand, 7, 8).
softAction(stand, 7, 9).
softAction(hit, 7, 11).%ace

softAction(hit,   8, 2).
softAction(hit,   8, 3).
softAction(hit,   8, 4).
softAction(hit,   8, 5).
softAction(hit,   8, 6).
softAction(stand, 8, 7).
softAction(stand, 8, 8).
softAction(stand, 8, 9).
softAction(hit, 8, 11).%ace

softAction(hit,   9, 2).
softAction(hit,   9, 3).
softAction(hit,   9, 4).
softAction(hit,   9, 5).
softAction(hit,   9, 6).
softAction(hit,   9, 7).
softAction(stand, 9, 8).
softAction(stand, 9, 9).
softAction(hit, 9, 11).%ace

softAction(hit,   10, 2).
softAction(hit,   10, 3).
softAction(hit,   10, 4).
softAction(hit,   10, 5).
softAction(hit,   10, 6).
softAction(hit,   10, 7).
softAction(stand, 10, 8).
softAction(stand, 10, 9).
softAction(hit, 10, 11).%ace

softAction(hit,   ace, 2).
softAction(hit,   ace, 3).
softAction(hit,   ace, 4).
softAction(hit,   ace, 5).
softAction(hit,   ace, 6).
softAction(hit,   ace, 7).
softAction(stand, ace, 8).
softAction(stand, ace, 9).
softAction(hit,   ace, 11).%ace
